<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminController
 */
class AdminControllerTest extends TestCase
{
    /**
     * @test
     */
    public function downloadBackupReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/downloadbackup');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function downloadYesterdayBackupReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/downloadyesterdaybackup');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function indexReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin');

        $response->assertOk();
        $response->assertViewIs('admin.dashboard');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function indexUsersReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/users');

        $response->assertOk();
        $response->assertViewIs('admin.usersdashboard');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function supervisorindexReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/supervisor');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
