<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\InterviewController
 */
class InterviewControllerTest extends TestCase
{
    /**
     * @test
     */
    public function export_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $interview = factory(\App\Interview::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get('export/{interview}/interview');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get('interviews/new');

        $response->assertOk();
        $response->assertViewIs('interview.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $interview = factory(\App\Interview::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->delete('interview/{interview}');

        $response->assertOk();
        $this->assertDeleted($interview);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $interview = factory(\App\Interview::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get('interview/{interview}/show');

        $response->assertOk();
        $response->assertViewIs('interview.view');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post('interviews', [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
