<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SortingController
 */
class SortingControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function downloadReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $interview = factory(\App\Interview::class)->create();
        $sorting = factory(\App\Sorting::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get('interview/{interview}/sorting/{sorting}/download');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function showReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $interview = factory(\App\Interview::class)->create();
        $sorting = factory(\App\Sorting::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get('interview/{interview}/sorting/{sorting}/show');

        $response->assertOk();
        $response->assertViewIs('sorting.view');

        // TODO: perform additional assertions
    }

    // test cases...
}
